version: '2'

services:
  nginx:
    build:
      context: ./arch-nginx/
    ports:
      - "80:80"
    volumes_from:
      - php
    volumes:
      - ./arch-nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./arch-nginx/conf/sites/:/etc/nginx/sites-enabled/
      - ./http/:/srv/http/  
    networks:
      - arch-lemp
  php:
    build:
      context: ./arch-php/
    ports:
      - "9000:9000"
    volumes:
      - ./http/:/srv/http/  
    networks:
      - arch-lemp
      
 

networks:
    arch-lemp:
        driver: bridge
